#!/usr/bin/env python3
"""
build_data.py — Convert EMPLOYEE_DATA_ONLINE.xlsx → data.js
============================================================
Usage:
    python build_data.py EMPLOYEE_DATA_ONLINE.xlsx

Output:
    data.js   (place in the same folder as Employee_Dashboard_v2.html)

For GitHub Pages / local use:
    1. Run this script whenever the Excel is updated.
    2. Commit both Employee_Dashboard_v2.html and data.js to your repo.
    3. Open Employee_Dashboard_v2.html in a browser (or serve via GitHub Pages).

To use the external data.js instead of the embedded data in the HTML:
    - Add  <script src="data.js"></script>  BEFORE the main dashboard <script>
    - Comment out or remove the `const RAW_DATA = [...]` block inside the HTML

Requirements:
    pip install pandas openpyxl
"""

import sys
import json
import pandas as pd

def build(excel_path: str, out_path: str = "data.js"):
    df = pd.read_excel(excel_path)
    df['Category'] = df['Category'].str.upper()

    CORE_METRICS = [
        'SERVICE SALES', 'PRODUCT SALES', 'SERVICE ABV', 'PRODUCT ABV',
        'TOTAL CLIENTS SERVICES', 'TOTAL CLIENTS PRODUCT',
        'EXISTING CLIENTS SERVICES', 'NEW CLIENTS SERVICES',
        '3 MONTH REPEAT CLIENTS', 'RETENTION %'
    ]
    months = ['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC']

    raw_data = []
    for _, row in df.drop_duplicates(subset=['EmployeeCode','YearNum']).iterrows():
        code = str(int(row['EmployeeCode']))
        year = int(row['YearNum'])
        emp = {
            'code': code,
            'name': str(row['EmployeeName']).upper(),
            'des': str(row['Designation']).upper(),
            'dep': str(row['Category']).upper(),
            'salon': str(row['Salon']),
            'tenure': float(row['Tenure']),
            'year': year,
            'brand': str(row['Brand'])
        }
        for metric in CORE_METRICS:
            mask = (
                (df['EmployeeCode'].astype(str) == code) &
                (df['YearNum'] == year) &
                (df['Category.1'] == metric)
            )
            rows = df[mask]
            if len(rows) > 0:
                vals = rows.iloc[0][months].fillna(0).tolist()
                emp[metric] = [float(v) for v in vals]
            else:
                emp[metric] = [0.0] * 12
        raw_data.append(emp)

    js_content = (
        "// Auto-generated by build_data.py — do not edit manually.\n"
        "// Re-run: python build_data.py EMPLOYEE_DATA_ONLINE.xlsx\n"
        f"// Records: {len(raw_data)}\n\n"
        "const RAW_DATA = " + json.dumps(raw_data, ensure_ascii=False, indent=2) + ";\n"
    )

    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(js_content)

    print(f"✅ Written {len(raw_data)} records to {out_path}")

if __name__ == "__main__":
    excel = sys.argv[1] if len(sys.argv) > 1 else "EMPLOYEE_DATA_ONLINE.xlsx"
    out = sys.argv[2] if len(sys.argv) > 2 else "data.js"
    build(excel, out)
